### ISSUE TITLE
AQM2 modpack. Golemancy. Parched crashes server.

### ISSUE THREAD

**Issue by racergsr** [emirik0l/Golemancy#1]
Using the AQM2 modpack. Created a parched golem with golemancy. Linked it to a chest. As soon as I put buckets in the chest and the golem reached for them the server went into a crash loop. It crashed every time someone joined (because the golem was still grabbing the buckets) until we removed the mod from the server.

**Comment by emirik0l** [comment]
I haven't been able to replicate this on a client/server running the latest version, can you confirm what version of the mod you were running and the error that was thrown by the server?

**Comment by emirik0l** [comment]
Ok, I loaded AQM2 and I think i've identified the issue.

**Comment by emirik0l** [comment]
This should hopefully be fixed in commit https://github.com/emirik0l/Golemancy/commit/e69ea261301c2d80107da5ca6f6a83661363ff8d
Please try using the newest version of Golemancy on here/curseforge and see if it resolves the problem for you.

**Comment by racergsr** [comment]
We'll give it a try. Thank you.

**Comment by racergsr** [comment]
[crash-2022-01-01_22.15.03-server.txt](https://github.com/emirik0l/Golemancy/files/7799580/crash-2022-01-01_22.15.03-server.txt)
Here is the initial crash from the bucket filling attempt for your reference.
