### ISSUE TITLE
Golem Armor

### ISSUE THREAD

**Issue by RedPug** [emirik0l/Golemancy#12]
Valiant golems can be killed very easily. I suggest adding Golem Armor, basically horse armor but for golems. These items would be craftable with their respective materials.

**Comment by emirik0l** [comment]
You can already get golems with armor by using terracotta or obsidian golems; the amount of armor they get is configurable.

**Comment by RedPug** [comment]
The armor given by those types isn't very high, though.

**Comment by emirik0l** [comment]
That's intended to prevent golems from being too strong; as I said, though, you can configure the mod to give them as much armor as you want.
