### ISSUE TITLE
Entropic Golems can't use tools

### ISSUE THREAD

**Issue by RedPug** [emirik0l/Golemancy#13]
From what I've seen through testing, Entropic golems won't use tools they have equipped. This might be useful if a player wants to golem to use a faster pickaxe to mine something, or wanted to use silk touch or fortune.

**Comment by emirik0l** [comment]
That's intended behavior, entropic golems always break at the same speed and don't use tools.

**Comment by RedPug** [comment]
is there a planned way to let them use silk touch or fortune? (for example, if you wanted to make a golem automatically mine stone from a generator, it would be able to actually collect the stone rather than cobblestone)

**Comment by emirik0l** [comment]
I may consider it for further mutations from the entropic golem, but probably not for the entropic golem itself.
