### ISSUE TITLE
Golems cannot interact with chests from other mods

### ISSUE THREAD

**Issue by bytebone** [emirik0l/Golemancy#2]
When using the "Expanded Storage" mod (https://modrinth.com/mod/expanded-storage), golems can be linked to these modded chests, but cannot take items in or out of said chest. Since I understand that it is impossible to provide support for every storage mod under the sun, I wonder if using the minecraft block tags would be an interesting option.
Admittedly, I haven't read either the Golemancy code to see how chests are identified, nor the Expanded Storage code to verify if block tags are used. 
Still, I'd love to see support for these modded chests. Hopefully, this can be achieved in a simple way.

If need be, I can supply additional info on the matter.

**Comment by emirik0l** [comment]
In theory, golems should be able to use any block entity that extends "ChestBlock" or implements "Inventory", so I'm surprised it's not compatible. I'll look into it and see what I can do, though!

Are there any other modded chest or inventory mods that golems were having issues with?

**Comment by bytebone** [comment]
This Chest mod was the only one I tested in this limited environment. i could test a different mod that adds forges to the game and see how the golems handle those. 
it might also be possible that the storage mod doesnt properly use the properties you mentioned. Might be worth a look into their sourcecode.

**Comment by emirik0l** [comment]
This turned out to be a very easy fix! Just tested with a Covetous golem on diamond chest, iron barrel, and a couple of the presents from Expanded Storage and it seems to work OK. Should be supported in the next version of Golemancy that releases.

![expanded-storage](https://user-images.githubusercontent.com/77687278/150514146-1dc7ba92-c7c7-423f-a1cc-a799a35d68b0.png)
