### ISSUE TITLE
Conflicct with Companion

### ISSUE THREAD

**Issue by Sirkilium** [emirik0l/Golemancy#4]
Golems not following you are not considered "sitting" so with Companion installed(which makes pets following you go through portals and not get trapped in unloading chunks) going through a nether portal or using a waystone makes all golems teleport to you. This includes ones following you(as intended) and those not following. Basically any that aren't in boats. Somewhat relatedly, I've noticed that golems have no concept of pathing and only walk in straight lines unless following a player.

**Comment by emirik0l** [comment]
Golems should use the same pathfinding as vanilla mobs (i.e. a wolf), so I'm not sure I can do much about their pathing. However, I'll look into the other issue.

**Comment by Sirkilium** [comment]
For an example of what I mean, if there's a covetous golem in a fence and an item outside it will continue to stare at the item outside that it has no way of reaching even if another item is dropped in a spot it can reach. Additionally they seems to frequently get stuck on blocks especially at heal level

**Comment by emirik0l** [comment]
What version of the mod is this on? The newest version (1.2.1)?

**Comment by Sirkilium** [comment]
I just checked the server and it is indeed 1.2.1

**Comment by emirik0l** [comment]
Thanks for the info, I'll continue looking into this.

**Comment by Sirkilium** [comment]
Thank you for all these fixes, they look excellent

**Comment by emirik0l** [comment]
Whew, that ended up being a lot more work than I thought! Hopefully that improves the performance of those golems and stops them from getting "obsessed" with stuff they can't reach as much; those changes will be available when version 1.2.2 comes out.
