### ISSUE TITLE
Slight issue

### ISSUE THREAD

**Issue by Sirkilium** [emirik0l/Golemancy#6]
Ran in to this "fun" error while playing on a server. [Pastebin:](https://bytebin.lucko.me/uK8zsHsX1i)
Crashy saved me from closing the game but logging back in revealed a few visual issues and I was stuck at 0-8 FPS.
![unknown](https://user-images.githubusercontent.com/58004954/152969741-e6980938-0a19-4467-8e11-f87b3b41fb18.png)

**Comment by emirik0l** [comment]
Annoying. Should be a pretty easy fix though

**Comment by emirik0l** [comment]
If possible, could you check if this quick fix build fixes your problem and behaves as expected?

https://github.com/emirik0l/Golemancy/releases/tag/v1.2.3

**Comment by Sirkilium** [comment]
Everything has been working perfectly since I restarted my launcher, and no one else on the server has encountered it. So I'm not sure how to replicate it

**Comment by emirik0l** [comment]
Fair enough. I'll close it for now, that fix should ensure that if it does break again it'll default to rendering golems as clay rather than crashing at least.
