### ISSUE TITLE
Insane "nearby" range for farming golems

### ISSUE THREAD

**Issue by RedPug** [emirik0l/Golemancy#7]
An 81x81 block square being covered by a single golem seems VERY excessive. I think this range should be reduced to perhaps a 33 block (16 on either side) side length.

**Comment by emirik0l** [comment]
The "nearby" range is affected by the golem's smarts, but I'll look into the farming golems and how sane the current radius is for them.

**Comment by emirik0l** [comment]
I don't actually see a problem with the search radius they have - the 81x81 square is for a golem with "perfect" smarts, who has a search radius of 40 blocks. You need to kill a wither to get those genes, so it doesn't feel inappropriate to me. Golems with lower smarts will have a radius of 10, 20 or 30 blocks.

However, I have made the golem search radius configurable, so you can lower the radius on your own game to the level you prefer. If you set the base value to 4, then a perfect golem will have a 16-block search radius.

**Comment by RedPug** [comment]
oh, that must be because I was grabbing the souls from the creative inventory.

**Comment by emirik0l** [comment]
Yep, souls from the creative inventory always have 100% perfect genes :) I'm thinking of adding some commands to spawn in soulstones with different genes at some point.
