### ISSUE TITLE
Tactile golems can't receive items automatically

### ISSUE THREAD

**Issue by RedPug** [emirik0l/Golemancy#8]
Tactile golems can use items such as shears, or place blocks in a specific spot. As it stands, there is no way to automatically give the golem more of the item once they've used it up. If a golem has a block in their hand, they will place it down, but won't have a way to pick another one up. I propose adding a mechanic where the golems can pick up items by getting the items dispensed onto them.

**Comment by RedPug** [comment]
Tactile golems also can't interact with entities (i.e. to shear sheep or milk cows, it also can't fill water bottles from source blocks)

**Comment by emirik0l** [comment]
Resolved; tactile golems can now pick up items that are dropped on the ground within 1.5 blocks of them (i.e. by a dispenser).
